modLoader="javafml"
loaderVersion="[37,)"
license="GPLv3"
issueTrackerURL="https://github.com/Autovw/AdvancedNetherite/issues"

[[mods]]
modId="advancednetherite"
version="1.4.0"
displayName="Advanced Netherite"
updateJSONURL="https://raw.githubusercontent.com/Autovw/ModUpdates/master/advancednetherite/update.json"
displayURL="https://github.com/Autovw/AdvancedNetherite/wiki"
logoFile="advancednetherite_banner.png"
#credits=""
authors="Autovw"
description='''
Advanced Netherite mod.

A developer friendly, open-source mod that adds in more types of Netherite!
Visit the Wiki for more information on everything this mod adds.
'''

[[dependencies.advancednetherite]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"
[[dependencies.advancednetherite]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18]"
ordering="NONE"
side="BOTH"

[modproperties.advancednetherite]
#Catalogue also supports items. Use "catalogueItemIcon" instead.
catalogueImageIcon="advancednetherite_logo.png" #Optional support for Cataloque mod.
configuredBackground="minecraft:textures/block/netherite_block.png" #Optional support for Configured mod.
